version: "3.7"
services:
  app:
    build:
      context: ""
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./../laravel:/var/www
    environment:
      - DB_HOST=database
    depends_on:
      - database
  web:
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - ./../laravel:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
  database:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD="
      - "MYSQL_ROOT_PASSWORD="
    ports:
      - "33061:3306"
